spring:
  jpa:
    properties:
      org.hibernate.envers:
        revision_type_field_name: revision_type
        revision_field_name: revision_id
    database-platform:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: '${DATABASE_CONNECTION_URL:jdbc:postgresql://localhost:5433/twitter}'
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 900
      max-idle: 200
      min-idle: 20

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
