version: '3.4'
services:

  config-server:
    container_name: config-server
    image: warleyvods/config-server
    ports:
      - '8083:8083'
    networks:
      - devnet
    depends_on:
      - discovery
    links:
      - discovery
    restart: on-failure

  discovery:
    container_name: discovery-server
    image: warleyvods/discovery-server
    ports:
      - '8081:8081'
    networks:
      - devnet

  gateway:
    container_name: gateway-server
    image: warleyvods/gateway-server
    ports:
    - '8080:8080'
    networks:
      - devnet
    depends_on:
      - discovery
    links:
      - discovery
    restart: on-failure

  hashtag-tracker:
    container_name: hashtag-tracker-server
    image: warleyvods/hashtag-tracker
    ports:
    - '8082:8082'
    networks:
      - devnet
    depends_on:
      - db
      - discovery
      - config-server
      - gateway
    links:
      - config-server
      - discovery
      - gateway
      - db
    restart: on-failure
  
  frontend:
    container_name: frontend
    image: warleyvods/frontend
    ports:
      - '80:8080'
    networks:
      - devnet
    depends_on:
      - hashtag-tracker
    links:
      - hashtag-tracker
    restart: on-failure

  db:
    image: postgres:10-alpine
    container_name: db
    hostname: db
    restart: always
    networks:
      - devnet
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=twitter
    volumes:
      - './data/pg_db:/var/lib/postgresql'
      - './data/pg_data:/var/lib/postgresql/data'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  devnet:
    driver: bridge
