version: '3.4'
services:
    db:
      image: postgres:10-alpine
      container_name: db
      hostname: db
      restart: always
      networks:
        - devnet
      ports:
        - 5433:5432
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=twitter
      volumes:
        - './data/pg_db:/var/lib/postgresql'
        - './data/pg_data:/var/lib/postgresql/data'
      ulimits:
        nofile:
          soft: 65536
          hard: 65536

networks:
  devnet:
    driver: bridge
